### PR TITLE
Unit test setup

### PR DESCRIPTION
**Pull request by changkon**
One thing I noticed is that when we aggregate movies, I'm checking only if the title is matching (which I think is ok for now), but when we merge the movie list, we should merge any information. For example, if one source has The Dark Knight movie and another movie source also has The Dark Knight movie but with genre, runtime etc populated, the aggregated movie list should contain The Dark Knight with all fields populated.

### CODE REVIEW

**Comment by changkon** [comment]
Can run tests using npm test in lambda folder

**Comment by Wal8800** [comment]
@changkon what about putting the test onto CI platform ?

**Comment by changkon** [comment]
@Wal8800 how? maybe can do after?

**Review by Wal8800 — APPROVED** [review]

**Comment by Wal8800** [comment]
think you can setup test on travis CI or other similar services. most of them should be free for public repo.

**Review by WesleyYep — APPROVED** [review]

**Pull request merged**
