### PR TITLE
Refactor merge

### PR DESCRIPTION
**Pull request by changkon**
Just updated callbacks to promises and edited file structure.
Needs to fix Lex still (someone can take that task) i.e. move it to a single intent.
Also probably good idea to do unit tests.

### CODE REVIEW

**Review by Wal8800 — CHANGES_REQUESTED** [review]
Need to remove the temp json file

**Comment by changkon** [comment]
names?

**Comment by WesleyYep** [comment]
should remove all the ones that start with out_
eg. out_MovieBot.json

**Comment by changkon** [comment]
@WesleyYep @Wal8800 updated

**Review by Wal8800 — APPROVED** [review]

**Pull request merged**
