### PR TITLE
Hydrate movie list

### PR DESCRIPTION
**Pull request by Wal8800**
So before aggregating the different movie list from different result, hydrate the movies with information so it can be use for processing. Right now it retrieve
- directors
- releaseDate
- trailerURL and trailerThumbnailURL

Key changes:

- decrease the es query size so there is less to hydrate
- included moment js to handle date comparison

### CODE REVIEW

**Review by WesleyYep — APPROVED** [review]
seems good, maybe make a unit test

**Review by WesleyYep — CHANGES_REQUESTED** [review]
hmm actually I test and it doesn't seem to hydrate something that looks like it should be hydrated

image

image

image

You can see although the hydrate call returns the movie that should match the name, after hydrating everything is still undefined

**Comment by Wal8800** [comment]
gggggggggg, got an examples ?

**Comment by WesleyYep** [comment]
just put it up, it's when I searched for actor "rahul roy"

**Comment by WesleyYep** [comment]
ok looks like its building the model well now.
Just another problem though

When searching for wonder woman, only the animated original wonder woman movie is shown

**Pull request merged**
